export const Countries = [
  "Serbia",
  "Nepal",
  "Kenya",
  "Uzbekistan",
  "Tajikistan",
  "Kyrgyzstan",
  "India",
  "United Arab Emirates",
  "Austria",
  "Germany",
  "Croatia",
  "Bosnia and Herzegovina",
  "Montenegro",
  "North Macedonia",
  "Albania",
  "Sri Lanka",
  "Philippines",
  "Bangladesh",
  "Pakistan",
  "Indonesia",
  "Vietnam",
  "Thailand",
  "Myanmar",
  "Egypt",
  "Morocco",
  "Tunisia",
  "Ghana",
  "Nigeria",
  "Ethiopia",
  "Uganda",
  "Tanzania",
  "South Africa",
  "Romania",
  "Bulgaria",
  "Hungary",
  "Slovakia",
  "Czech Republic",
  "Poland",
  "Moldova",
  "Georgia",
  "Armenia",
  "Azerbaijan",
  "Kazakhstan",
  "Turkey"
];
